### ISSUE TITLE
duplicate 1.AD.R?

### ISSUE THREAD

**Issue by dhetting** [dinman/r-sensitivity#2]
@dinman Does `1.AD.2.R` supercede `1.AD.R` and can `1.AD.R` therefore be removed from the repo?

**Comment by dinman** [comment]
AD.2.R uses a different basis for the alternate dataset designation (B.bar). 1.AD.R compares the group "B" to the full study design less the runs in B (B.bar). 1.AD,R compares B to another user-defined group (B.bar).

**Comment by dinman** [comment]
You got access now


https://github.com/dinman/r-sensitivity/invitations
